/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import unit1GettingStarted.chp02.PrintHello;
import unit1GettingStarted.chp02.Summary;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        PrintHello.helloFromCupOfJava();

        Summary.summaryOfChapter2();
    }
}
